name: Docker Runner Example

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: k8s-runner

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker environment
        uses: docker/setup-docker@v1

      - name: Build Docker image
        run: |
          docker build -t my-docker-image .
        
      - name: Run Docker container
        run: |
          docker run --rm -v /var/run/docker.sock:/var/run/docker.sock my-docker-image
        
