name: Docker Runner Example

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: k8s-runner

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker environment
        uses: docker/setup-buildx-action@v1

      - name: Docker Hun login
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_PASSWORD }}


      - name: Run Docker container
        run: |
          docker version \ 
          docker run --rm -v /var/run/dockershim.sock:/var/run/dockershim.sock dk9340/sujin
