name: Docker Workflow
on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: k8s-runner
    container:
      image: docker:stable

    steps:
      - name: Run Docker Container
        run: docker run -d --name my-container nginx
