name: Docker Workflow
on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: k8s-runner
    container:
      image: docker:stable

    steps:

      - name: Check Docker version
        run: docker version
